# Generated by Django 5.2.4 on 2025-08-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="date_born",
            field=models.DateField(
                blank=True,
                help_text="Введите дату рождения",
                null=True,
                verbose_name="",
            ),
        ),
    ]
